name: hex
description: Easy hexadecimal convertion using dart:convert API.
version: 0.1.2
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-hex

environment:
  sdk: ^2.11.0-213.1.beta

dev_dependencies:
  test: ^1.16.0-nullsafety.5
